# Generated by Django 5.2.7 on 2025-11-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_nome_cliente_nome_completo_remove_cliente_cep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_completo',
            new_name='nomeCompleto',
        ),
    ]
