# Generated by Django 5.2.7 on 2025-11-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidade_estoque',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='precoVenda',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_alteracao',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='Geral', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='estoqueMinimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='Geral', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(default='Geral', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(max_length=100),
        ),
    ]
